#ifndef OPYPHONGTOSPLINE_H_
#define OPYPHONGTOSPLINE_H_

enum
{
	ID_PHONGTOSPLINE_SELECTION = 1000,
	ID_PHONGTOSPLINE_INPUTLINK = 1001,
	ID_PHONGTOSPLINE_SPLINETYPE = 1002,
	ID_PHONGTOSPLINE_LINEAR = 0,
	ID_PHONGTOSPLINE_AKIMA = 1,
	ID_PHONGTOSPLINE_BSPLINE = 2,
	ID_PHONGTOSPLINE_SUBDIVISIONS = 1003,
	ID_PHONGTOSPLINE_OVERRIDETYPE = 1004,
	ID_PHONGTOSPLINE_ISOPARMMODE = 1005,
	ID_PHONGTOSPLINE_CLOSE = 1006
};

#endif // OPYEDGETOSPLINE_H_