CONTAINER opyphongtosplineobject
{
	NAME opyphongtosplineobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LINK ID_PHONGTOSPLINE_INPUTLINK {}
		STRING ID_PHONGTOSPLINE_SELECTION {}
		BOOL ID_PHONGTOSPLINE_ISOPARMMODE {}
		BOOL ID_PHONGTOSPLINE_CLOSE {}
		BOOL ID_PHONGTOSPLINE_OVERRIDETYPE {}
		LONG ID_PHONGTOSPLINE_SPLINETYPE
		{
			CYCLE
			{
				ID_PHONGTOSPLINE_LINEAR;
				ID_PHONGTOSPLINE_AKIMA;
				ID_PHONGTOSPLINE_BSPLINE;
			}
		}
		LONG ID_PHONGTOSPLINE_SUBDIVISIONS { MIN 0; }

	}
}
